import type { Config } from "@react-router/dev/config";

export default {
  appDirectory: "src",
  // SPA mode: React Router renders entirely client-side. Pre-rendering still
  // works for the listed routes. Setting ssr:true with Firebase static hosting
  // caused checkout crashes because Firebase serves the home-page SSR HTML for
  // unknown routes, and React Router v7 then tried to fetch /checkout.data
  // from a server that doesn't exist — Firebase returned HTML (200 OK), and
  // the JSON.parse of that HTML threw: "Unexpected token '<', <!DOCTYPE..."
  ssr: false,
  prerender: [
    "/",
    "/menu",
    "/wellness",
    "/performance",
    "/clinical",
    "/team",
    "/faq",
    "/dish/activated-charcoal-smoothie",
    "/dish/aglio-olio-chicken",
    "/dish/aglio-olio-prawns",
    "/dish/aglio-olio-veg",
    "/dish/alfredo-pasta-chicken",
    "/dish/alfredo-pasta-prawns",
    "/dish/alfredo-pasta-veg",
    "/dish/aliya-viral-beetroot-curd",
    "/dish/almond-chicken-salad",
    "/dish/amaranth-porridge-with-blueberry-sauce",
    "/dish/antioxidant-detox",
    "/dish/apple-cinnamon-smoothie",
    "/dish/arrabbiata-chicken",
    "/dish/arrabbiata-prawns",
    "/dish/arrabbiata-veg",
    "/dish/avocado-toast",
    "/dish/avocado-toast-with-poached-boiled-egg",
    "/dish/avocado-toast-with-sunny-side-up",
    "/dish/barbeque-chicken-burrito-wrap",
    "/dish/barbeque-grilled-chicken-rice-bowl",
    "/dish/barbeque-paneer-fiesta-rice-bowl",
    "/dish/blueberry-smoothie",
    "/dish/broccoli-almond-soup",
    "/dish/broccoli-babycorn-tomato-salad",
    "/dish/broccoli-lemon-chicken-salad",
    "/dish/cheese-omelette",
    "/dish/cheese-tomato-omelette",
    "/dish/cheesy-delight-nachos",
    "/dish/chia-lemonade-smoothie",
    "/dish/chicken-amigos-sandwich",
    "/dish/chicken-caesar-story-salad",
    "/dish/chicken-hummus-pita",
    "/dish/chicken-pita-pockets-with-hummus",
    "/dish/chicken-tikka-sandwich-with-ranch-yoghurt",
    "/dish/chickpea-peanut-tabbouleh-salad",
    "/dish/chilli-chipotle-paneer-burrito-wrap",
    "/dish/chilli-chipotle-paneer-rice-bowl",
    "/dish/chipotle-chicken-burrito-wrap",
    "/dish/chipotle-grilled-chicken-rice-bowl",
    "/dish/classic-bread-omelette-2-egg",
    "/dish/classic-nachos",
    "/dish/classic-vegetable-poha",
    "/dish/coke-can",
    "/dish/cream-of-broccoli",
    "/dish/cream-of-chicken",
    "/dish/cream-of-mushroom",
    "/dish/creamy-egg-white-sandwich",
    "/dish/crispy-mushroom-burrito-wrap",
    "/dish/crispy-mushroom-rice-bowl",
    "/dish/crispy-peri-peri-chicken-burrito-wrap",
    "/dish/crispy-peri-peri-chicken-rice-bowl",
    "/dish/crispy-peri-peri-mushroom-burrito-wrap",
    "/dish/crispy-peri-peri-mushroom-rice-bowl",
    "/dish/crispy-peri-peri-potato-rice-bowl",
    "/dish/dates-banana-smoothie",
    "/dish/diet-coke-can",
    "/dish/exotic-amaranth-blueberry-yogurt",
    "/dish/exotic-egg-bhurji",
    "/dish/exotic-fruit-bowl",
    "/dish/falafal-hummus-wrap",
    "/dish/falafal-pita-pockets-with-hummus",
    "/dish/falafel-garden-salad",
    "/dish/french-omelette-sweet-savoury",
    "/dish/fruity-sprout-salad",
    "/dish/fruity-yogurt",
    "/dish/greek-roman-chicken-salad",
    "/dish/greek-roman-veg-salad",
    "/dish/healthy-liver-juice",
    "/dish/healthy-whole-wheat-chicken-tikka-wrap",
    "/dish/healthy-whole-wheat-paneer-wrap",
    "/dish/healthy-whole-wheat-tofu-wrap",
    "/dish/high-protein-chicken-omelette",
    "/dish/hot-n-sour-soup-chicken",
    "/dish/hot-n-sour-soup-veg",
    "/dish/hummus-pita-classic",
    "/dish/hummus-pita-with-falafel",
    "/dish/hydrating-watermelon-juice",
    "/dish/lebanese-hummus-salad",
    "/dish/lemon-mint-ice-tea-smoothie",
    "/dish/manchow-soup-chicken",
    "/dish/manchow-soup-veg",
    "/dish/masala-bread-omelette-2-egg",
    "/dish/millets-bread-loaf",
    "/dish/millets-poha-barnyard",
    "/dish/moong-dal-chilla-with-curd",
    "/dish/mushroom-omelette",
    "/dish/nutella-toast-brown-bread",
    "/dish/nutella-toast-white-bread",
    "/dish/paneer-tikka-burrito-wrap",
    "/dish/peanut-butter-banana-smoothie",
    "/dish/peri-peri-paneer-burrito-wrap",
    "/dish/peri-peri-paneer-fiesta-rice-bowl",
    "/dish/pesto-pasta-chicken",
    "/dish/pesto-pasta-prawns",
    "/dish/pesto-pasta-veg",
    "/dish/plain-omelette",
    "/dish/power-house-smoothie",
    "/dish/quinoa-khichdi",
    "/dish/quinoa-upma",
    "/dish/ragi-dates-eggless-brownie",
    "/dish/roast-chicken-russian",
    "/dish/signature-quinoa-salad",
    "/dish/smoked-chicken-cheese-omelette",
    "/dish/smokey-chicken-salad",
    "/dish/spinach-mushroom-omelette",
    "/dish/thums-up-can",
    "/dish/tomato-basil-omelette",
    "/dish/tomato-basil-soup",
    "/dish/two-boiled-eggs",
    "/dish/veg-amigos-sandwich",
    "/dish/veg-caesar-story-salad",
    "/dish/veg-loaded-bread-omelette-2-egg",
    "/dish/zero-calorie-mint-mojito",
  ],
} satisfies Config;
