import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  layout("routes/Layout.tsx", [
    index("pages/Home.tsx"),
    route("menu", "pages/Menu.tsx"),
    route("dish/:slug", "pages/Dish.tsx"),
    route("cart", "pages/Cart.tsx"),
    route("checkout", "pages/Checkout.tsx"),
    route("track", "pages/Track.tsx"),
    route("orders", "pages/Orders.tsx"),
    route("subscribe", "pages/Subscribe.tsx"),
    route("subscriptions", "pages/Subscriptions.tsx"),
    route("meal-planner", "pages/WeeklyPlanner.tsx"),
    route("rewards", "pages/Rewards.tsx"),
    route("preferences", "pages/Preferences.tsx"),
    route("account", "pages/Account.tsx"),
    route("account/addresses", "pages/Addresses.tsx"),
    route("terms", "pages/Terms.tsx"),
    route("privacy", "pages/Privacy.tsx"),
    route("wellness", "pages/Wellness.tsx"),
    route("performance", "pages/Performance.tsx"),
    route("clinical", "pages/Clinical.tsx"),
    route("team", "pages/Team.tsx"),
    route("team/:slug", "pages/TeamMember.tsx"),
    route("plans", "pages/RdPlans.tsx"),
    route("plans/:slug", "pages/RdPlanDetail.tsx"),
    route("rd", "pages/RdDirectory.tsx"),
    route("rd/:slug", "pages/RdProfile.tsx"),
    route("appointments", "pages/Appointments.tsx"),
    route("rd-console", "pages/RdConsoleGate.tsx"),
    route("checkout-appointment", "pages/CheckoutAppointment.tsx"),
    route("faq", "pages/Faq.tsx"),
    route("admin", "pages/AdminIndexGate.tsx"),
    route("admin/ops", "pages/AdminOpsDashboardGate.tsx"),
    route("admin/ai-runs", "pages/AdminAiRunsGate.tsx"),
    route("admin/ops-agent", "pages/AdminOpsAgentGate.tsx"),
    route("admin/cms-agent", "pages/AdminCmsAgentGate.tsx"),
    route("admin/forecasting", "pages/AdminForecastingGate.tsx"),
    route("admin/menu-engineering", "pages/AdminMenuEngineeringGate.tsx"),
    route("admin/analytics", "pages/AdminAnalyticsGate.tsx"),
    route("admin/support-tickets", "pages/AdminSupportTicketsGate.tsx"),
    route("rd-partners", "pages/RdPartnersLanding.tsx"),
    route("rd-partners/apply", "pages/RdPartnersWizard.tsx"),
    route("admin/rd-applications", "pages/AdminRdApplicationsGate.tsx"),
    route("group/:code", "pages/GroupOrder.tsx"),
    route("recipes", "pages/Recipes.tsx"),
    route("recipes/:slug", "pages/RecipeDetail.tsx"),
    route("admin/moderation", "pages/AdminModerationGate.tsx"),
    route("admin/community-moderation", "pages/AdminCommunityModerationGate.tsx"),
    route("challenges", "pages/Challenges.tsx"),
    route("challenges/:slug", "pages/ChallengeDetail.tsx"),
    route("corporate", "pages/Corporate.tsx"),
    route("corporate/invite/:token", "pages/CorporateInvite.tsx"),
    route("corporate/:slug", "pages/CorporateAdmin.tsx"),
    route("corporate/:slug/lunch-planner", "pages/CorporateLunchPlanner.tsx"),
    route("office-lunch/:id", "pages/OfficeLunch.tsx"),
    route("admin/sales-console", "pages/AdminSalesConsoleGate.tsx"),
    route("admin/sales-console/:slug", "pages/AdminSalesAccountGate.tsx"),
    route("vouchers", "pages/Vouchers.tsx"),
    route("premium", "pages/Premium.tsx"),
    route("marketplace", "pages/Marketplace.tsx"),
    route("marketplace/:slug", "pages/MarketplaceItem.tsx"),
    route("login", "pages/Login.tsx"),
    route("admin/login", "pages/AdminLogin.tsx"),
    route("*", "pages/not-found.tsx")
  ])
] satisfies RouteConfig;
