import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import deliveryRouter from "./delivery";
import fulfillmentRouter from "./fulfillment";
import supportAgentRouter from "./supportAgent";
import coachAgentRouter from "./coachAgent";
import opsRouter from "./ops";
import subscriptionsRouter from "./subscriptions";
import loyaltyRouter from "./loyalty";
import preferencesRouter from "./preferences";
import rdAdvisoryRouter from "./rdAdvisory";
import bundlesRouter from "./bundles";
import groupOrdersRouter from "./groupOrders";
import wellnessRouter from "./wellness";
import aiRunsRouter from "./aiRuns";
import opsAgentRouter from "./opsAgent";
import forecastingRouter from "./forecasting";
import menuRouter from "./menu";
import menuAssetsRouter from "./menuAssets";
import cmsAgentRouter from "./cmsAgent";
import menuEngineeringRouter from "./menuEngineering";
import analyticsRouter from "./analytics";
import supportTicketsRouter from "./supportTickets";
import recipesRouter from "./recipes";
import teamProfilesRouter from "./teamProfiles";
import challengesRouter from "./challenges";
import rdPartnersRouter from "./rdPartners";
import corporateRouter from "./corporate";
import addonsRouter from "./addons";
import premiumRouter from "./premium";
import marketplaceRouter from "./marketplace";
import dishRationalesRouter from "./dishRationales";
import mealPlansRouter from "./mealPlans";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(deliveryRouter);
router.use(fulfillmentRouter);
router.use(supportAgentRouter);
router.use(coachAgentRouter);
router.use("/ops", opsRouter);
router.use(subscriptionsRouter);
router.use(loyaltyRouter);
router.use(preferencesRouter);
router.use(rdAdvisoryRouter);
router.use(bundlesRouter);
router.use(groupOrdersRouter);
router.use(wellnessRouter);
router.use(aiRunsRouter);
router.use(opsAgentRouter);
router.use(forecastingRouter);
router.use(menuRouter);
router.use(menuAssetsRouter);
router.use(cmsAgentRouter);
router.use(menuEngineeringRouter);
router.use(analyticsRouter);
router.use(supportTicketsRouter);
router.use(recipesRouter);
router.use(teamProfilesRouter);
router.use(challengesRouter);
router.use(rdPartnersRouter);
router.use(corporateRouter);
router.use(addonsRouter);
router.use(premiumRouter);
router.use(marketplaceRouter);
router.use(dishRationalesRouter);
router.use(mealPlansRouter);

export default router;
